site_name: MkDocs中文文档
site_url: https://mkdocs.zimoapps.com
site_description: 非官方的MkDocs中文文档。
site_author: zimo

repo_url: https://github.com/zimocode/mkdocs-docs-zh/
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - 主页: index.md
    - 用户指南:
        - 编写文档: user-guide/writing-your-docs.md
        - 设置文档样式: user-guide/styling-your-docs.md
        - 配置文件: user-guide/configuration.md
        - 部署文档: user-guide/deploying-your-docs.md
        - 自定义主题: user-guide/custom-themes.md
        - 插件: user-guide/plugins.md
    - 关于:
        - 发行说明: about/release-notes.md
        - 贡献: about/contributing.md
        - 许可: about/license.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>. <a href="http://www.beian.miit.gov.cn" target="_blank">蜀ICP备19036239号</a>
# google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
